package com.combatlogger.util;

import com.google.common.collect.ImmutableSet;

import java.util.*;
import java.util.stream.Collectors;

import static net.runelite.api.gameval.NpcID.*;

public class BossIds
{
	public static final ImmutableSet<Integer> VERZIK_P1_END = ImmutableSet.of(
			VERZIK_PHASE1_TO2_TRANSITION_STORY, // entry mode
			VERZIK_PHASE1_TO2_TRANSITION, // normal mode
			VERZIK_PHASE1_TO2_TRANSITION_HARD // hard mode
	);

	/**
	 * List of Boss IDs
	 * This differs from NpcIdsToTrack in that boss ids are used to "upgrade" a fight to a boss, or start a new fight if a boss targets a player
	 **/
	public static final Set<Integer> BOSS_IDS = new HashSet<>(Arrays.asList(
			RAT_BOSS_INSTANCE, // Scurrius solo
			RAT_BOSS_NORMAL, // Scurrius group
			GODWARS_ARMADYL_AVATAR, // Kree'arra
			GODWARS_SARADOMIN_AVATAR, // Commander Zilyana
			GODWARS_BANDOS_AVATAR, // General Graardor
			GODWARS_ZAMORAK_AVATAR, // K'ril Tsutsaroth
			NEX,
			NEX_SPAWNING,
			NEX_SOULSPLIT,
			NEX_DEFLECT,
			NEX_DYING,
			KALPHITE_QUEEN,
			KALPHITE_FLYINGQUEEN,
			SWAN_KALPHITE_1, // Kalphite Queen
			SWAN_KALPHITE_2, // Kalphite Queen
			SARACHNIS,
			SCORPIA,
			ABYSSALSIRE_SIRE_STASIS_SLEEPING,
			ABYSSALSIRE_SIRE_STASIS_AWAKE,
			ABYSSALSIRE_SIRE_STASIS_STUNNED,
			ABYSSALSIRE_SIRE_PUPPET,
			ABYSSALSIRE_SIRE_WANDERING,
			ABYSSALSIRE_SIRE_PANICKING,
			ABYSSALSIRE_SIRE_APOCALYPSE,
			LEVIATHAN,
			LEVIATHAN_QUEST,
			LEVIATHAN_CUTSCENE,
			LEVIATHAN_CUTSCENE_FAKE,
			WHISPERER,
			WHISPERER_MELEE,
			WHISPERER_QUEST,
			WHISPERER_MELEE_QUEST,
			WHISPERER_CUTSCENE,
			VARDORVIS,
			VARDORVIS_QUEST,
			VARDORVIS_CUTSCENE,
			VARDORVIS_BASE_QUEST,
			VARDORVIS_BASE_POSTQUEST,
			VARDORVIS_BASE,
			DUKE_SUCELLUS_INACTIVE,
			DUKE_SUCELLUS_ASLEEP,
			DUKE_SUCELLUS_AWAKE,
			DUKE_SUCELLUS_DEAD,
			DUKE_SUCELLUS_INACTIVE_QUEST,
			DUKE_SUCELLUS_ASLEEP_QUEST,
			DUKE_SUCELLUS_AWAKE_QUEST,
			DUKE_SUCELLUS_DEAD_QUEST,
			RAIDS_TEKTON_WAITING,
			RAIDS_TEKTON_WALKING_STANDARD,
			RAIDS_TEKTON_FIGHTING_STANDARD,
			RAIDS_TEKTON_WALKING_ENRAGED,
			RAIDS_TEKTON_FIGHTING_ENRAGED,
			RAIDS_TEKTON_HAMMERING,
			RAIDS_ICEDEMON_NONCOMBAT,
			RAIDS_ICEDEMON_COMBAT,
			RAIDS_VANGUARD_DORMANT,
			RAIDS_VANGUARD_WALKING,
			RAIDS_VANGUARD_MELEE,
			RAIDS_VANGUARD_RANGED,
			RAIDS_VANGUARD_MAGIC,
			RAIDS_VESPULA_FLYING,
			RAIDS_VESPULA_ENRAGED,
			RAIDS_VESPULA_WALKING,
			RAIDS_VESPULA_PORTAL,
			RAIDS_VASANISTIRIO_WALKING,
			RAIDS_VASANISTIRIO_HEALING,
			RAIDS_DOGODILE_SUBMERGED,
			RAIDS_DOGODILE_JUNIOR,
			RAIDS_DOGODILE,
			OLM_HEAD,
			TOB_MAIDEN_100,
			TOB_MAIDEN_70,
			TOB_MAIDEN_50,
			TOB_MAIDEN_30,
			TOB_MAIDEN_DYING_A,
			TOB_MAIDEN_DYING_B,
			TOB_BLOAT,
			TOB_BLOAT_STORY,
			TOB_BLOAT_HARD,
			TOBQUEST_BLOAT,
			NYLOCAS_BOSS_SPAWNING,
			NYLOCAS_BOSS_MELEE,
			NYLOCAS_BOSS_MAGIC,
			NYLOCAS_BOSS_RANGED,
			NYLOCAS_BOSS_SPAWNING_STORY,
			NYLOCAS_BOSS_MELEE_STORY,
			NYLOCAS_BOSS_MAGIC_STORY,
			NYLOCAS_BOSS_RANGED_STORY,
			NYLOCAS_BOSS_SPAWNING_HARD,
			NYLOCAS_BOSS_MELEE_HARD,
			NYLOCAS_BOSS_MAGIC_HARD,
			NYLOCAS_BOSS_RANGED_HARD,
			TOBQUEST_NYLOBOSS,
			TOB_SOTETSEG_NONCOMBAT,
			TOB_SOTETSEG_COMBAT,
			TOB_SOTETSEG_NONCOMBAT_STORY,
			TOB_SOTETSEG_COMBAT_STORY,
			TOB_SOTETSEG_NONCOMBAT_HARD,
			TOB_SOTETSEG_COMBAT_HARD,
			TOB_XARPUS_STATIC,
			TOB_XARPUS_FEEDING,
			TOB_XARPUS_COMBAT,
			XARPUS_DEATH,
			TOB_XARPUS_STATIC_STORY,
			TOB_XARPUS_FEEDING_STORY,
			TOB_XARPUS_COMBAT_STORY,
			XARPUS_DEATH_STORY,
			TOB_XARPUS_STATIC_HARD,
			TOB_XARPUS_FEEDING_HARD,
			TOB_XARPUS_COMBAT_HARD,
			XARPUS_DEATH_HARD,
			TOBQUEST_XARPUS,
			VERZIK_INITIAL,
			VERZIK_PHASE1,
			VERZIK_PHASE1_TO2_TRANSITION,
			VERZIK_PHASE2,
			VERZIK_PHASE2_TO3_TRANSITION,
			VERZIK_PHASE3,
			VERZIK_DEATH_BAT,
			VERZIK_INITIAL_STORY,
			VERZIK_PHASE1_STORY,
			VERZIK_PHASE1_TO2_TRANSITION_STORY,
			VERZIK_PHASE2_STORY,
			VERZIK_PHASE2_TO3_TRANSITION_STORY,
			VERZIK_PHASE3_STORY,
			VERZIK_DEATH_BAT_STORY,
			VERZIK_INITIAL_HARD,
			VERZIK_PHASE1_HARD,
			VERZIK_PHASE1_TO2_TRANSITION_HARD,
			VERZIK_PHASE2_HARD,
			VERZIK_PHASE2_TO3_TRANSITION_HARD,
			VERZIK_PHASE3_HARD,
			VERZIK_DEATH_BAT_HARD,
			TOBQUEST_VERZIK,
			TOA_BABA,
			TOA_BABA_COFFIN,
			TOA_BABA_DIGGING,
			AKKHA_SPAWN,
			AKKHA_MELEE,
			AKKHA_RANGE,
			AKKHA_MAGE,
			AKKHA_ENRAGE_SPAWN,
			AKKHA_ENRAGE_INITIAL,
			AKKHA_ENRAGE,
			AKKHA_ENRAGE_DUMMY,
			TOA_KEPHRI_BOSS_SHIELDED,
			TOA_KEPHRI_BOSS_WEAK,
			TOA_KEPHRI_BOSS_ENRAGE,
			TOA_KEPHRI_BOSS_DEAD,
			TOA_ZEBAK,
			TOA_ZEBAK_TAIL,
			TOA_ZEBAK_ENRAGED,
			TOA_ZEBAK_DEAD,
			TOA_ZEBAK_TAIL_DEAD,
			TOA_WARDENS_P1_OBELISK_NPC_INACTIVE,
			TOA_WARDENS_P1_OBELISK_NPC,
			TOA_WARDEN_ELIDINIS_PHASE2_MAGE,
			TOA_WARDEN_ELIDINIS_PHASE2_RANGE,
			TOA_WARDEN_ELIDINIS_PHASE2_EXPOSED,
			TOA_WARDEN_TUMEKEN_PHASE2_MAGE,
			TOA_WARDEN_TUMEKEN_PHASE2_RANGE,
			TOA_WARDEN_TUMEKEN_PHASE2_EXPOSED,
			TOA_WARDEN_TUMEKEN_CORE,
			TOA_WARDEN_ELIDINIS_CORE,
			TOA_WARDEN_ELIDINIS_PHASE3,
			TOA_WARDEN_TUMEKEN_PHASE3,
			TOA_WARDEN_ELIDINIS_PHASE3_CHARGING,
			TOA_WARDEN_TUMEKEN_PHASE3_CHARGING,
			CORP_BEAST,
			KING_DRAGON, // King Black Dragon
			VORKATH_SLEEPING_NOOP,
			VORKATH_SLEEPING,
			VORKATH_QUEST,
			VORKATH,
			VORKATH_TRANSMOG,
			SNAKEBOSS_BOSS_RANGED, // Zulrah
			SNAKEBOSS_BOSS_MELEE, // Zulrah
			SNAKEBOSS_BOSS_MAGIC, // Zulrah
			DARK_SEREN,
			DARK_SEREN_PHANTOM,
			DARK_SEREN_CUTSCENE,
			DARK_SEREN_CUTSCENE_TRAPPED,
			HYDRABOSS,
			HYDRABOSS_P1_TRANSITION,
			HYDRABOSS_P2_TRANSITION,
			HYDRABOSS_P3_TRANSITION,
			HYDRABOSS_4,
			HYDRABOSS_3,
			HYDRABOSS_2,
			HYDRABOSS_FINALDEATH,
			HYDRABOSS_TRANSMOG,
			GB_MOSSGIANT, // Bryophyta
			CALLISTO,
			CALLISTO_SINGLES, // Artio
			CERBERUS_ATTACKING,
			CERBERUS_SITTING,
			CERBERUS_RESETTING,
			CRYSTAL_HUNLLEF_MELEE,
			CRYSTAL_HUNLLEF_RANGED,
			CRYSTAL_HUNLLEF_MAGIC,
			CRYSTAL_HUNLLEF_DEATH,
			CRYSTAL_HUNLLEF_MELEE_HM, // Corrupted Hunllef
			CRYSTAL_HUNLLEF_RANGED_HM, // Corrupted Hunllef
			CRYSTAL_HUNLLEF_MAGIC_HM, // Corrupted Hunllef
			CRYSTAL_HUNLLEF_DEATH_HM, // Corrupted Hunllef
			MOLE_GIANT, // Giant Mole
			CLANCUP_MOLE_GIANT, // Giant Mole
			HESPORI,
			TOBQUEST_HESPORI,
			TRAIL_MIMIC_NONCOMBAT, // The Mimic
			TRAIL_MIMIC_COMBAT, // The Mimic
			NIGHTMARE_PHASE_01,
			NIGHTMARE_PHASE_02,
			NIGHTMARE_PHASE_03,
			NIGHTMARE_WEAK_PHASE_01,
			NIGHTMARE_WEAK_PHASE_02,
			NIGHTMARE_WEAK_PHASE_03,
			NIGHTMARE_BLAST,
			NIGHTMARE_INITIAL,
			NIGHTMARE_DYING,
			NIGHTMARE_ENTRY_READY,
			NIGHTMARE_ENTRY_OPEN,
			NIGHTMARE_ENTRY_CLOSED_01,
			NIGHTMARE_ENTRY_CLOSED_02,
			NIGHTMARE_ENTRY_CLOSED_03,
			NIGHTMARE_CHALLENGE_PHASE_01,
			NIGHTMARE_CHALLENGE_PHASE_02,
			NIGHTMARE_CHALLENGE_PHASE_03,
			NIGHTMARE_CHALLENGE_WEAK_PHASE_01,
			NIGHTMARE_CHALLENGE_WEAK_PHASE_02,
			NIGHTMARE_CHALLENGE_WEAK_PHASE_03,
			NIGHTMARE_CHALLENGE_BLAST,
			NIGHTMARE_CHALLENGE_INITIAL,
			NIGHTMARE_CHALLENGE_DYING,
			HILLGIANT_BOSS, // Obor
			MUSPAH,
			MUSPAH_MELEE,
			MUSPAH_SOULSPLIT,
			MUSPAH_FINAL,
			CATA_BOSS, // Skotizo
			TZHAAR_FIGHTCAVE_SWARM_BOSS, // TzTok-Jad
			INFERNO_JAD,
			INFERNO_TZKALZUK_PLACEHOLDER, // TzKal-Zuk
			JAD_CHALLENGE_JAD,
			CLANCUP_TZHAAR_FIGHTCAVE_SWARM_BOSS,
			VENENATIS,
			VENENATIS_SINGLES, // Spindel
			CLANCUP_VENENATIS,
			VETION,
			VETION_2,
			VETION_TRANS,
			VETION_SINGLE, // Calvar'ion
			VETION_2_SINGLE, // Calvar'ion
			VETION_TRANS_SINGLE,
			VETION_TRANS_2_SINGLE,
			COLOSSEUM_SOL_P1,
			COLOSSEUM_BOSS_SEATED,
			SLAYER_KRAKEN_BOSS,
			SLAYER_KRAKEN_BOSS_WHIRLPOOL
	));
	public static final Map<String, List<String>> BOSS_TO_MINIONS;
	public static final Map<String, String> MINION_TO_BOSS;

	static
	{
		BOSS_TO_MINIONS = Map.of(
				"Nylocas Vasilias", List.of("Nylocas Hagios", "Nylocas Ischyros", "Nylocas Toxobolos")
		);

		MINION_TO_BOSS = BOSS_TO_MINIONS.entrySet().stream()
				.flatMap(entry -> entry.getValue().stream().map(minion -> Map.entry(minion, entry.getKey())))
				.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
	}
}
